# Generated by Django 6.0.1 on 2026-02-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('reply', 'New Reply'), ('review', 'New Review'), ('enrollment', 'New Join'), ('report', 'New Report')], max_length=20),
        ),
    ]
