# Generated by Django 6.0.1 on 2026-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_steps',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='paths.pathstep'),
        ),
    ]
