# Generated by Django 6.0.1 on 2026-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='target_id',
            field=models.CharField(help_text='ID of the path, comment, or user being reported', max_length=255),
        ),
    ]
