# Generated by Django 6.0.1 on 2026-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0009_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
